# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  setup-bazel:
    description: |
      Setup the Bazel build system used for building Android projects
    steps:
      - run:
          name: Add Bazel Apt repository
          command: |
            sudo apt install curl gnupg
            curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
            sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
            echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
      - run:
          name: Install Bazel from Apt
          command: sudo apt update && sudo apt install bazel
  setup-dependencies:
    steps:
      - run: apt-get -y update &&
            apt-get -y install
              g++-10
              git
jobs:
  build_with_cmake:
    docker:
      - image: ubuntu:20.04
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - setup-dependencies
      - run: apt-get -y update &&
            apt-get -y install cmake
      - checkout
      - run: mkdir build
      - run: cd build && cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10
      - run: cd build && make -j 2
      - run: cd build/test && ctest -V
  build_with_bazel:
    docker:
      - image: ubuntu:20.04
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - setup-dependencies
      - setup-bazel
      - checkout
      - run: bazel run test:matrix_test
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "run_test"
  run_test:
    jobs:
      - build_with_cmake
      - build_with_bazel