# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build_test:
    docker:
      - image: ubuntu:20.04
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: apt-get -y update &&
            apt-get -y install
              g++
              git
              cmake
      - checkout
      - run: mkdir build
      - run: cd build && cmake ..
      - run: cd build && make -j 2
      - run: cd build/test && ctest -V
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "run_test"
  run_test:
    jobs:
      - build_test
      